### ISSUE TITLE
Kodi 19 compatibility

### ISSUE THREAD

**Issue by Forceflow** [add-ons/plugin.video.yelo#32] opened 2020-11-22 10:01 UTC
This is probably known, but the standard Android TV version of Kodi has switched to 19.0 beta, and the Yelo TV app stops working after the automatic upgrade. It stays in an "installed" state, but is automatically disabled.

I don't know if it's a compatibility issue, or just a flag that needs to be switched. Similar add-ons like VRTnu or VTMGo (which depends on adaptive-inputstream as well) seem to work.

**Comment by michaelarnauts** [comment] 2020-11-22 12:50
@Forceflow I think the code itself is compatible with Kodi 19, but you'll need to modify the `addons.xml` file so the `xbmc.python` is `3.0.0`, like this:

        <import addon="xbmc.python" version="3.0.0"/>

I don't have a Telenet account, so I can't really test this though. This could be easily fixed by using the release workflow from #30 so the right zip-files are made automatically.

**Comment by dagwieers** [comment] 2020-11-22 16:33
This is a duplicate of #26 but from a different perspective ;-)

**Closed by dagwieers** 2020-11-22 16:33 UTC
Labels: duplicate
